website:
    bitly:
        username:  benjaminmgross@yahoo.com
        OAthToken: ce729e3340cbbcd1e0213d74fa66f243a36ab008
    amazon:
        username: benjaminmgross@yahoo.com
        OAthToken: fall04
    zillow:
        username: benjaminmgross@yahoo.com
        OAthToken: X1-ZWz1b5tnui3x8r_3pg0i



